### ISSUE TITLE
How to start on the technical development problem research

### ISSUE THREAD

**Issue by yanbx** [fadams/docker-gui#4]
Hello, ask for so many days, I'm not, I for the spice, the spice - web - client learning time, in addition to the links do they use and their underlying structure, then want to use for the development of its content, but the development of this agreement, the field, I am still a stranger, for example, I see the spice - web - I see the client is js, he is also based on javascript, for his development I don't know where to start, and spice,I see that you mentioned XSPICE in the article. I understand that this is another encapsulation of SPICE protocol, right?What is the underlying development language for this protocol?Where do I start?

**Comment by fadams** [comment]
I don't really know what you are asking here.

I've tried to be helpful by answering questions and giving you links to the SPICE documentation and the HTML client GitHub pages but those are not my projects I simply tried to get them working in Docker. If you want to understand more about how they work you really need to speak with the maintainers of those projects.

Re: "I see the spice - web - I see the client is js, he is also based on javascript, for his development I don't know where to start". Yes the flexVDI/eyeos spice-web-client is HTML5 + CSS + Javascript. If you don't understand Javascript, which is what I think you are saying then this is not the repository to be asking for advice on that. There are many online tutorials. When I modified the Dockerfile you saw yesterday you really need to compare that with the original one. The changes were pretty minimal - mostly dynamically changing styles via Javascript. This is a reasonable starting point for Javascript https://www.w3schools.com/js/DEFAULT.asp and I'd recommend the book Javascript the Definitive Guide by David Flanagan published by O'Reilly.

Re "I see that you mentioned XSPICE in the article. I understand that this is another encapsulation of SPICE protocol, right?What is the underlying development language for this protocol?Where do I start?" If you looked at the links I sent you yesterday you could find that information out for yourself. https://www.spice-space.org/xspice.html https://cgit.freedesktop.org/xorg/driver/xf86-video-qxl/tree/README.xspice .

I've actually told you this previously but Xspice is an X Server that is also a SPICE server. It's not an encapsulation of the protocol. As far as I'm aware it is written in C.
