### ISSUE TITLE
About the audio playback problem in Chapter 4- Local-Applications

### ISSUE THREAD

**Issue by yanbx** [fadams/docker-gui#5]
Hi, I'm starting to learn the sound part, do you need to configure something for the "aplay: set_params:1343: sample format not available" error and "aplay: set_params:1349: channel count not available" error when executing your two examples?

\11-remote-virtual-desktops\spice\ubuntu-18.04-gnome-spice: I see you have loaded the audio in but you can't hear it in the remote tool or browser?So I started to study and study again from Chapter 4. Could you please help me directly analyze it?

**Comment by fadams** [comment]
On `do you need to configure something for the "aplay: ` which specific example in chapter 4?

On my desktop I don't need to configure anything.

Most of the audio examples in the book assume that you are running a fairly standard Linux Desktop and are running PulseAudio locally.

On "\11-remote-virtual-desktops\spice\ubuntu-18.04-gnome-spice: I see you have loaded the audio in but you can't hear it in the remote tool or browser?" well assuming that you are logging in to the Ubuntu Gnome desktop via a browser do you have audio from any other Web sites available in the browser you are using? You definitely need to rule out the possibility that you have issues with your own native desktop audio first.

**Comment by yanbx** [comment]
Thank you, this problem can be closed, I have solved it, it is still my local environment problem
