### ISSUE TITLE
After landing successfully about remote, enter desktop not to enter password problem

### ISSUE THREAD

**Issue by yanbx** [fadams/docker-gui#6]
After I've worked out this problem, I have another idea that I want to make sure that after you log in remotely, you have to enter a UNIX password to get to the desktop. This password can remove the user and go directly to the desktop without loading Xauth

**Comment by fadams** [comment]
This is not an issue with this repo.

I believe that you are asking whether it is possible to log straight into the Desktop without having to enter a password in the Display Manager (login screen) - that has nothing to do with Xauth BTW, which relates to authentication with the X Server.

If that is what you are asking then I believe that it is possible. You would have to modify the LightDM configuration.

I did a quick web search and found this: https://unix.stackexchange.com/questions/398880/remove-user-and-password-at-login-in-debian-9-stretch

This is really the sort of thing that you need to research for yourself.
