### ISSUE TITLE
About the multi-screen problem

### ISSUE THREAD

**Issue by yanbx** [fadams/docker-gui#7]
Does the SPICE protocol not support dual screens?We can't do a two-screen display

**Comment by fadams** [comment]
This is not an issue with this repo.

You really do need to learn how to do your own research

I believe that SPICE does support multiple monitors though you may have to look at the configuration https://www.spice-space.org/multiple-monitors.html

https://people.freedesktop.org/~teuf/spice-doc/html/ch02s07.html

If you actually look in the `ubuntu-gnome-spice:18.04` Dockerfile there is a line
```
    sed -i 's/#Option "NumHeads" "4"/Option "NumHeads" "1"/' /etc/X11/spiceqxl.xorg.conf && \
```
It's just possible that removing this line will be enough to support 4 monitors, but I have no idea.

I've specifically said these examples represent a starting point.
